@baseUrl = https://localhost:1367/authentication

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Test protected route with token
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc1MjgzNDMxNywiaXNzIjoiQXU1IiwiYXVkIjoiQXU1LWNsaWVudHMifQ.xphnP102Y37BRLnWS3d8xcN5snfReqOUyOIOY4bhEYc"

GET {{baseUrl}}/test-auth
Authorization: Bearer {{token}}
