//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Au5.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Au5.Application.Common.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with BotFather.
        /// </summary>
        internal static string FailedCommunicateWithBotFather {
            get {
                return ResourceManager.GetString("FailedCommunicateWithBotFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add bot to meeting.
        /// </summary>
        internal static string FailedToAddBot {
            get {
                return ResourceManager.GetString("FailedToAddBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Config System.
        /// </summary>
        internal static string FailedToConfigSystem {
            get {
                return ResourceManager.GetString("FailedToConfigSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction must be either &apos;ltr&apos; or &apos;rtl&apos;..
        /// </summary>
        internal static string InvalidDirection {
            get {
                return ResourceManager.GetString("InvalidDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidLanguageFormat.
        /// </summary>
        internal static string InvalidLanguageFormat {
            get {
                return ResourceManager.GetString("InvalidLanguageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Must be liveCaption or liveAudio.
        /// </summary>
        internal static string InvalidMeetingTranscriptionModel {
            get {
                return ResourceManager.GetString("InvalidMeetingTranscriptionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long..
        /// </summary>
        internal static string InvalidPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Url.
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username format..
        /// </summary>
        internal static string InvalidUsernameFormat {
            get {
                return ResourceManager.GetString("InvalidUsernameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect..
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than Zero..
        /// </summary>
        internal static string MustBeMoreThanZero {
            get {
                return ResourceManager.GetString("MustBeMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property can not be empty.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Already Configured , You can set ForceUpdate=true..
        /// </summary>
        internal static string SystemAlreadyConfigured {
            get {
                return ResourceManager.GetString("SystemAlreadyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemIsNotConfigured.
        /// </summary>
        internal static string SystemIsNotConfigured {
            get {
                return ResourceManager.GetString("SystemIsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized user, You can&apos;t do this action..
        /// </summary>
        internal static string UnAuthorizedAction {
            get {
                return ResourceManager.GetString("UnAuthorizedAction", resourceCulture);
            }
        }
    }
}
