global using Au5.Application.Models.Dtos.MeetingDtos;
global using Au5.Application.Models.Messages;
global using Au5.Application.Services.Interfaces;
global using Au5.Domain.Common;
global using Au5.Domain.Entities;
global using Au5.Shared;
global using FluentValidation;
global using FluentValidation.Results;
global using Mediator;
