global using Au5.Application;
global using Au5.Application.Features.Implement;
global using Au5.Application.Interfaces;
global using Au5.Application.Models.Messages;
global using Au5.BackEnd;
global using Au5.BackEnd.Hubs;
global using Au5.Infrastructure;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.SignalR;
